DROP DATABASE IF EXISTS MovieActorDB;
CREATE DATABASE MovieActorDB;
USE MovieActorDB;


CREATE TABLE MovieGenre (

genreID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(255) NOT NULL,
`description` VARCHAR(10000) NOT NULL
);

CREATE TABLE Movie (
movieID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(255),
rating FLOAT NULL,
`length` INT NOT NULL,
 genre INT NULL,
 FOREIGN KEY (genre) REFERENCES MovieGenre (genreID)
);

CREATE TABLE Actor(
actorID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
fName VARCHAR(255) NULL,
lName VARCHAR(255) NULL,
dateOfBirth DATE NOT NULL
);

CREATE TABLE ActorAppearsIn (
    actorID INT NOT NULL,
    movieID INT NOT NULL,
    CONSTRAINT PK_ActorAppearsIn PRIMARY KEY (actorID, movieID),
    FOREIGN KEY (actorID) REFERENCES Actor (actorID),
    FOREIGN KEY (movieID) REFERENCES Movie (movieID)

);
